apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/kubeflow/community-distribution/example?ref=f09f3eeaa25cc852665f460497a42b7fc68639ac
  - gpu-placement-policy.yaml
  - retained-storage.yaml

patches:
  - target:
      group: kubeflow.org
      version: v1beta1
      kind: Profile
      name: kubeflow-user-example-com
    patch: |-
      - op: replace
        path: /metadata/name
        value: gods-mlops
      - op: replace
        path: /spec/owner/name
        value: user@example.com
