apiVersion: v1
kind: ConfigMap
metadata:
  name: gods-mlops-ingestion-config
  namespace: gods-mlops
data:
  GODS_MLOPS_S3_ENDPOINT_URL: http://gods-mlops-storage-s3.gods-mlops.svc.cluster.local:8333
  GODS_MLOPS_S3_BUCKET: gods-samples
  GODS_MLOPS_S3_REGION: us-east-1
  POSTGRES_DB: gods_ingestion
  POSTGRES_USER: gods_ingestion
